import { CATEGORIES } from './data.js'

export const ALL_FOODS = [
  { name: 'Poma', category: 'Fruita' },
  { name: 'Plàtan', category: 'Fruita' },
  { name: 'Taronja', category: 'Fruita' },
  { name: 'Llimona', category: 'Fruita' },
  { name: 'Mandarina', category: 'Fruita' },
  { name: 'Maduixa', category: 'Fruita' },
  { name: 'Pera', category: 'Fruita' },
  { name: 'Kiwi', category: 'Fruita' },
  { name: 'Alvocat', category: 'Fruita' },
  { name: 'Raïm', category: 'Fruita' },
  { name: 'Síndria', category: 'Fruita' },
  { name: 'Préssec', category: 'Fruita' },
  { name: 'Patata', category: 'Verdura' },
  { name: 'Ceba', category: 'Verdura' },
  { name: 'All', category: 'Verdura' },
  { name: 'Tomàquet', category: 'Verdura' },
  { name: 'Enciam', category: 'Verdura' },
  { name: 'Espinacs', category: 'Verdura' },
  { name: 'Pastanaga', category: 'Verdura' },
  { name: 'Pebrot', category: 'Verdura' },
  { name: 'Carbassó', category: 'Verdura' },
  { name: 'Carabassa', category: 'Verdura' },
  { name: 'Albergínia', category: 'Verdura' },
  { name: 'Cogombre', category: 'Verdura' },
  { name: 'Bròquil', category: 'Verdura' },
  { name: 'Coliflor', category: 'Verdura' },
  { name: 'Col', category: 'Verdura' },
  { name: 'Espàrrecs', category: 'Verdura' },
  { name: 'Carxofa', category: 'Verdura' },
  { name: 'Porro', category: 'Verdura' },
  { name: 'Api', category: 'Verdura' },
  { name: 'Pèsols', category: 'Verdura' },
  { name: 'Mongetes', category: 'Verdura' },
  { name: 'Moniato', category: 'Verdura' },
  { name: 'Alfàbrega', category: 'Verdura' },
  { name: 'Romaní', category: 'Verdura' },
  { name: 'Julivert', category: 'Verdura' },
  { name: 'Pollastre', category: 'Carn' },
  { name: 'Vedella', category: 'Carn' },
  { name: 'Porc', category: 'Carn' },
  { name: 'Xai', category: 'Carn' },
  { name: 'Pernil', category: 'Carn' },
  { name: 'Botifarra', category: 'Carn' },
  { name: 'Llom', category: 'Carn' },
  { name: 'Carn picada', category: 'Carn' },
  { name: 'Cansalada', category: 'Carn' },
  { name: 'Salmó', category: 'Peix' },
  { name: 'Tonyina', category: 'Peix' },
  { name: 'Bacallà', category: 'Peix' },
  { name: 'Gambes', category: 'Peix' },
  { name: 'Calamars', category: 'Peix' },
  { name: 'Musclos', category: 'Peix' },
  { name: 'Pop', category: 'Peix' },
  { name: 'Llobarro', category: 'Peix' },
  { name: 'Sardines', category: 'Peix' },
  { name: 'Seitons', category: 'Peix' },
  { name: 'Cloïsses', category: 'Peix' },
  { name: 'Llet', category: 'Làctics' },
  { name: 'Iogurt', category: 'Làctics' },
  { name: 'Formatge', category: 'Làctics' },
  { name: 'Mantega', category: 'Làctics' },
  { name: 'Nata', category: 'Làctics' },
  { name: 'Mozzarella', category: 'Làctics' },
  { name: 'Mató', category: 'Làctics' },
  { name: 'Ous', category: 'Ous' },
  { name: 'Pa', category: 'Pa i cereals' },
  { name: 'Arròs', category: 'Pa i cereals' },
  { name: 'Pasta', category: 'Pa i cereals' },
  { name: 'Espagueti', category: 'Pa i cereals' },
  { name: 'Macarrons', category: 'Pa i cereals' },
  { name: 'Fideus', category: 'Pa i cereals' },
  { name: 'Farina', category: 'Pa i cereals' },
  { name: 'Flocs de civada', category: 'Pa i cereals' },
  { name: 'Llevat', category: 'Pa i cereals' },
  { name: 'Galetes', category: 'Pa i cereals' },
  { name: 'Torrades', category: 'Pa i cereals' },
  { name: 'Quinoa', category: 'Pa i cereals' },
  { name: 'Cereals', category: 'Pa i cereals' },
  { name: 'Aigua', category: 'Begudes' },
  { name: 'Suc', category: 'Begudes' },
  { name: 'Cervesa', category: 'Begudes' },
  { name: 'Vi', category: 'Begudes' },
  { name: 'Cafè', category: 'Begudes' },
  { name: 'Te', category: 'Begudes' },
  { name: 'Cava', category: 'Begudes' },
  { name: 'Olives', category: 'Conserves' },
  { name: 'Tomàquet triturat', category: 'Conserves' },
  { name: 'Sardines en conserva', category: 'Conserves' },
  { name: 'Espàrrecs en conserva', category: 'Conserves' },
  { name: 'Llenties', category: 'Conserves' },
  { name: 'Cigrons', category: 'Conserves' },
  { name: 'Canelons', category: 'Plats preparats' },
  { name: 'Lasanya', category: 'Plats preparats' },
  { name: 'Amanida preparada', category: 'Plats preparats' },
  { name: 'Gaspatxo', category: 'Plats preparats' },
  { name: 'Hummus', category: 'Plats preparats' },
  { name: 'Puré de verdures', category: 'Plats preparats' },
  { name: 'Sopa de verdures', category: 'Plats preparats' },
  { name: 'Guisat', category: 'Plats preparats' },
  { name: 'Truita de patates', category: 'Plats preparats' },
  { name: 'Croquetes preparades', category: 'Plats preparats' },
  { name: 'Detergent rentadora', category: 'Drogueria' },
  { name: 'Detergent rentavaixelles', category: 'Drogueria' },
  { name: 'Lleixiu', category: 'Drogueria' },
  { name: 'Suavitzant', category: 'Drogueria' },
  { name: 'Netejavidres', category: 'Drogueria' },
  { name: 'Paper de cuina', category: 'Drogueria' },
  { name: 'Paper higiènic', category: 'Drogueria' },
  { name: 'Sabó de mans', category: 'Drogueria' },
  { name: 'Esponja', category: 'Drogueria' },
  { name: 'Fregall', category: 'Drogueria' },
  { name: 'Baieta', category: 'Drogueria' },
  { name: 'Bosses d\'escombraries', category: 'Drogueria' },
  { name: 'Ambientador', category: 'Drogueria' },
  { name: 'Xampú', category: 'Drogueria' },
  { name: 'Pasta de dents', category: 'Drogueria' },
  { name: 'Oli', category: 'Altres' },
  { name: 'Sal', category: 'Altres' },
  { name: 'Pebre', category: 'Altres' },
  { name: 'Pimentó', category: 'Altres' },
  { name: 'Sucre', category: 'Altres' },
  { name: 'Mel', category: 'Altres' },
  { name: 'Vinagre', category: 'Altres' },
  { name: 'Maionesa', category: 'Altres' },
  { name: 'Canyella', category: 'Altres' },
  { name: 'Farigola', category: 'Altres' }
]

export function foodsByCategory(food) {
  return CATEGORIES.includes(food.category) ? food.category : 'Altres'
}
